"""Constants package for the multi-agent workflow system."""

from .agents import (
    AGENT_NAMES,
    AGENT_EXECUTION_ORDER,
    AGENT_TIMEOUTS,
    AGENT_RETRY_ATTEMPTS,
    AGENT_PRIORITIES,
    AGENT_REQUIRED_INPUTS,
    AGENT_OUTPUT_KEYS,
    AGENT_DESCRIPTIONS
)

from .mcp import (
    MCP_SERVER_TYPES,
    MCP_CONNECTION_STATUS,
    MCP_ERROR_CODES,
    MCP_RETRY_STRATEGY,
    MCP_CONNECTION_POOL,
    MCP_HEALTH_CHECK,
    MCP_LOGGING,
    MCP_SECURITY,
    MCP_PERFORMANCE
)

from .workflow import (
    WORKFLOW_STATUS,
    WORKFLOW_STEPS,
    WORKFLOW_STEP_DESCRIPTIONS,
    WORKFLOW_STEP_ORDER,
    WORKFLOW_STEP_TIMEOUTS,
    WORKFLOW_STEP_RETRIES,
    WORKFLOW_EXECUTION_MODES,
    WORKFLOW_PARALLEL_STEPS,
    WORKFLOW_CONDITIONAL_STEPS,
    WORKFLOW_ERROR_HANDLING,
    WORKFLOW_MONITORING,
    WORKFLOW_RESULT_STORAGE
)

from .ai_models import (
    OPENAI_MODELS,
    ANTHROPIC_MODELS,
    GOOGLE_MODELS,
    EMBEDDING_MODELS,
    TTS_MODELS,
    VECTOR_DB_PROVIDERS,
    VECTOR_DB_CONFIGS,
    WEB_CRAWLING_TOOLS,
    WEB_CRAWLING_CONFIGS,
    QUALITY_WEIGHTS
)

from .prompts import (
    PERSONALIZE_SYSTEM_PROMPT,
    QUERY_WRITER_SYSTEM_PROMPT,
    SEARCHER_SYSTEM_PROMPT,
    DB_CONSTRUCTOR_SYSTEM_PROMPT,
    RESEARCHER_SYSTEM_PROMPT,
    CRITIC_SYSTEM_PROMPT,
    SCRIPT_WRITER_SYSTEM_PROMPT,
    TTS_SYSTEM_PROMPT,
    PERSONALIZE_ANALYSIS_PROMPT,
    AI_RESEARCH_EXPERT_PROMPT,
    DATA_ANALYSIS_EXPERT_PROMPT,
    RESEARCH_CRITIC_DETAILED_PROMPT,
    PODCAST_SCRIPT_WRITER_DETAILED_PROMPT
)

from .configuration import (
    LLM_MODELS,
    EMBEDDING_MODELS,
    VECTOR_DB_PROVIDERS,
    TTS_PROVIDERS,
    WEB_CRAWLING_CONFIGS,
    CHUNKING_CONFIGS,
    QUALITY_THRESHOLDS,
    QUALITY_WEIGHTS,
    LOGGING_CONFIGS,
    WORKFLOW_CONFIGS,
    MCP_SERVER_DEFAULTS,
    WEB_CRAWLING_TOOL_CONFIGS
)

from .model_params import (
    OPENAI_DEFAULT_PARAMS,
    OPENAI_CRITIC_PARAMS,
    OPENAI_CRITIC_FALLBACK_PARAMS,
    OPENAI_SEARCHER_PARAMS,
    OPENAI_SEARCHER_FALLBACK_PARAMS,
    OPENAI_SCRIPT_WRITER_PARAMS,
    OPENAI_SCRIPT_WRITER_FALLBACK_PARAMS,
    OPENAI_RESEARCHER_PARAMS,
    OPENAI_PERSONALIZE_PARAMS,
    ANTHROPIC_SCRIPT_WRITER_PARAMS,
    AGENT_TIMEOUTS,
    CHUNK_PROCESSING,
    BATCH_PROCESSING,
    REPORTER_CONFIG,
    TOKEN_LIMITS,
    DEFAULT_MODELS,
    SUMMARIZER_CONFIG,
    WEB_CRAWLING_CONFIG,
    FILE_PROCESSING
)

__all__ = [
    # Agents
    "AGENT_NAMES",
    "AGENT_EXECUTION_ORDER",
    "AGENT_TIMEOUTS",
    "AGENT_RETRY_ATTEMPTS",
    "AGENT_PRIORITIES",
    "AGENT_REQUIRED_INPUTS",
    "AGENT_OUTPUT_KEYS",
    "AGENT_DESCRIPTIONS",
    
    # MCP
    "MCP_SERVER_TYPES",
    "MCP_CONNECTION_STATUS",
    "MCP_ERROR_CODES",
    "MCP_RETRY_STRATEGY",
    "MCP_CONNECTION_POOL",
    "MCP_HEALTH_CHECK",
    "MCP_LOGGING",
    "MCP_SECURITY",
    "MCP_PERFORMANCE",
    
    # Workflow
    "WORKFLOW_STATUS",
    "WORKFLOW_STEPS",
    "WORKFLOW_STEP_DESCRIPTIONS",
    "WORKFLOW_STEP_ORDER",
    "WORKFLOW_STEP_TIMEOUTS",
    "WORKFLOW_STEP_RETRIES",
    "WORKFLOW_EXECUTION_MODES",
    "WORKFLOW_PARALLEL_STEPS",
    "WORKFLOW_CONDITIONAL_STEPS",
    "WORKFLOW_ERROR_HANDLING",
    "WORKFLOW_MONITORING",
    "WORKFLOW_RESULT_STORAGE",
    
    # AI Models
    "OPENAI_MODELS",
    "ANTHROPIC_MODELS",
    "GOOGLE_MODELS",
    "EMBEDDING_MODELS",
    "TTS_MODELS",
    "VECTOR_DB_PROVIDERS",
    "VECTOR_DB_CONFIGS",
    "WEB_CRAWLING_TOOLS",
    "WEB_CRAWLING_CONFIGS",
    "QUALITY_WEIGHTS",
    
    # Prompts
    "PERSONALIZE_SYSTEM_PROMPT",
    "QUERY_WRITER_SYSTEM_PROMPT",
    "SEARCHER_SYSTEM_PROMPT",
    "DB_CONSTRUCTOR_SYSTEM_PROMPT",
    "RESEARCHER_SYSTEM_PROMPT",
    "CRITIC_SYSTEM_PROMPT",
    "SCRIPT_WRITER_SYSTEM_PROMPT",
    "TTS_SYSTEM_PROMPT",
    "PERSONALIZE_ANALYSIS_PROMPT",
    "AI_RESEARCH_EXPERT_PROMPT",
    "DATA_ANALYSIS_EXPERT_PROMPT",
    "RESEARCH_CRITIC_DETAILED_PROMPT",
    "PODCAST_SCRIPT_WRITER_DETAILED_PROMPT",
    
        # Configuration
    "LLM_MODELS",
    "EMBEDDING_MODELS", 
    "VECTOR_DB_PROVIDERS",
    "TTS_PROVIDERS",
    "WEB_CRAWLING_CONFIGS",
    "CHUNKING_CONFIGS",
    "QUALITY_THRESHOLDS",
    "QUALITY_WEIGHTS",
    "LOGGING_CONFIGS",
    "WORKFLOW_CONFIGS",
    "MCP_SERVER_DEFAULTS",
    "WEB_CRAWLING_TOOL_CONFIGS",
    
    # Model Parameters
    "OPENAI_DEFAULT_PARAMS",
    "OPENAI_CRITIC_PARAMS",
    "OPENAI_CRITIC_FALLBACK_PARAMS",
    "OPENAI_SEARCHER_PARAMS",
    "OPENAI_SEARCHER_FALLBACK_PARAMS",
    "OPENAI_SCRIPT_WRITER_PARAMS",
    "OPENAI_SCRIPT_WRITER_FALLBACK_PARAMS",
    "OPENAI_RESEARCHER_PARAMS",
    "OPENAI_PERSONALIZE_PARAMS",
    "ANTHROPIC_SCRIPT_WRITER_PARAMS",
    "AGENT_TIMEOUTS",
    "CHUNK_PROCESSING",
    "BATCH_PROCESSING",
    "REPORTER_CONFIG",
    "TOKEN_LIMITS",
    "DEFAULT_MODELS",
    "SUMMARIZER_CONFIG",
    "WEB_CRAWLING_CONFIG",
    "FILE_PROCESSING"
]
